location                           = "swedencentral"
prefix                             = "uc1a2"
environment                        = "dev"
default_language                   = "en-US"
logic_app_website_run_from_package = "1"
